[package]
name = "zeph-memory"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tokio = { workspace = true, features = ["rt"] }
tracing.workspace = true
zeph-llm = { path = "../zeph-llm" }

[lints]
workspace = true
