[package]
name = "zeph-memory"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
zeph-llm = { path = "../zeph-llm" }

[lints]
workspace = true
