[package]
name = "zeph-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
mcp = ["dep:zeph-mcp"]
self-learning = ["zeph-skills/self-learning"]

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
toml.workspace = true
tracing.workspace = true
zeph-llm.workspace = true
zeph-mcp = { workspace = true, optional = true, features = ["qdrant"] }
zeph-memory.workspace = true
zeph-skills = { workspace = true, features = ["qdrant"] }
zeph-tools.workspace = true

[dev-dependencies]
serial_test.workspace = true
tempfile.workspace = true

[lints]
workspace = true
